apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: <namespace>
  labels:
    app: money-tracker
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  selector:
    app: money-tracker
  type: LoadBalancer